# Generated by Django 5.1.4 on 2024-12-16 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dynamics', '0004_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptedrequest',
            name='accepted_by',
            field=models.ForeignKey(default=24, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acceptedrequest',
            name='request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Dynamics.solicitud'),
            preserve_default=False,
        ),
    ]
