# Generated by Django 5.1.4 on 2024-12-18 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dynamics', '0008_remove_acceptedrequest_accepted_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='request',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='request',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='sender',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='message',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notification_type',
        ),
        migrations.DeleteModel(
            name='AcceptedRequest',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
