# Generated by Django 5.1.4 on 2024-12-18 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dynamics', '0011_mensaje'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mensaje',
        ),
    ]
