# Generated by Django 5.1.4 on 2024-12-18 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dynamics', '0012_delete_mensaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='request',
        ),
        migrations.RemoveField(
            model_name='message',
            name='request',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.DeleteModel(
            name='AcceptedRequest',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
